module.exports = {
  urlxmls: 'http://infomatricula.espoch.edu.ec/',
  codigoPaq: '893',
  codigoPaqSenescyt: '895',
  codigoPaqMinEducacion: '899',
  codigoMSP: '901',
  codigoSRICompleto: '6112',
  codigoSRIDatos: '6113',
  codigoSRIContactos: '6114',
  codigoSRIGeneral: '896',
  codigoESPOCHMSP: '901',
  codigoESPOCH_MINEDUC:'6115',
  codigoESPOCHMINEDUCEstudiantes:'6116',
  tipoCedulaEstudiante: 'CedulaRepresentante',
  usuariodinardap: 'InEtSoHrV1',
  clavedinardap: 'krRvkxPA+J/IV!',
  urlwsdl: "https://interoperabilidad.dinardap.gob.ec/interoperador?wsdl",
  urlwsdl2: "https://interoperabilidad.dinardap.gob.ec/interoperador-v2?wsdl",
  urladmision: "https://apinivelacionevaluacion.espoch.edu.ec/api_m4/m_admision/",
  urladmisionsenescyt: "https://apinivelacionevaluacion.espoch.edu.ec/api_m4/m_senescyt/"
}